version: 1.0.{build}
image: Visual Studio 2015
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
  - call Script/installAGS.cmd
  - call Script/buildAGSGame.cmd
  - call Script/packageArtifacts.cmd
artifacts:
  - path: Compiled/Windows/DungeonHands-windows.zip
    name: DungeonHands-windows.zip
  - path: Compiled/Linux/DungeonHands-linux.tar.gz
    name: DungeonHands-linux.tar.gz
