version: 1.0.{build}
image: Visual Studio 2015
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
  - call Script/installAGS.cmd
  - call Script/buildAGSGame.cmd
  - call Script/packageArtifacts.cmd
artifacts:
  - path: Compiled/Windows/DungeonHands_Windows.zip
    name: DungeonHands_Windows.zip
  - path: Compiled/Linux/DungeonHands_Linux.tar.gz
    name: DungeonHands_Linux.tar.gz
