trigger:
- master

pool:
  vmImage: 'vs2015-win2012r2'

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  submodules: recursive 

- task: BatchScript@1
  inputs:
    filename: ags-game-ci-utils/installAGS.cmd

- task: BatchScript@1
  inputs:
    filename: ags-game-ci-utils/buildAGSGame.cmd
    arguments: $(Build.SourcesDirectory)

- task: BatchScript@1
  inputs:
    filename: ags-game-ci-utils/packageArtifacts.cmd
    arguments: $(Build.SourcesDirectory)
