name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: call dev_scripts\install_dependencies.cmd
        shell: cmd
      - name: Build game
        run: call dev_scripts\build_game.cmd
        shell: cmd
      - name: Package game
        run: call dev_scripts\package_game.cmd
        shell: cmd
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2        
        with:
          path: |
            dev_scripts/DIST/*          
          if-no-files-found: error
